greeting:
  message: "hello"

quarkus:
  datasource:
    reactive: 
      ~: false
    db-kind: postgresql
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    jdbc:
      url: ${DB_JDBC_HOST}
      validation-query-sql: SELECT 1

  hibernate-orm:
    database:
      default-schema: restaurant
      generation:
        ~: drop-and-create
        create-schemas: true

# Redis
  redis:
    devservices:
      enabled: false
    hosts: redis://localhost:6379
  
# Swagger
  swagger-ui:
    always-include: true

